sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 125004
  alioss:
      endpoint: oss-cn-beijing.aliyuncs.com
      bucketName: bucket-cy117
      accessKeyId: LTAI5tST6fu9NoRYffe5ySSe
      accessKeySecret: vOp2LEQ3Kx6RZcOYI94p20TzSxxcqL
spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password: 125004